spring:
  mail:
    protocol: smtp
    host: localhost
    port: 2525
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          from: demo@no-reply.com
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
          naver:
            client-name: Naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            redirect-uri: ${OAUTH2_NAVER_REDIRECT_URI:http://localhost:8080/login/oauth2/code/naver}
          kakao:
            client-name: Kakao
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email
            redirect-uri: ${OAUTH2_KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  issuer: ${JWT_ISSUER:demo}
  access-token:
    secret: ${JWT_ACCESS_TOKEN_SECRET:7cdfbf76e6b145aa9fbf76e6b1b5aa377159cc2b45f3406899cc2b45f350680e2a6dfe20118045abadfe20118015abb9e9ca4155f79e45638a4155f79eb5633c0e931d407847437a931d407847d37a499a9f4466d74f441a9f4466d74fe41abc873dc08201fc4fc4bdc08201fcafc40a0e04d5e10b9c4a7984d5e10b9c8a79bb03122d8533e4493d922d8533e4993dbc4a6c19f5276f4c33ac19f5276fcc3360}
    expiration-seconds: 900 # 15 minutes
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_SECRET:b281a4d6f98b453481a4d6f98b35340d1ba2c44cb94b44fea2c44cb94b44feb0194a682e60094e728a682e60098e72fec66764a006984d65a764a006981d65cc67f7325b2aa04ddfb7325b2aa07ddf678c3011ec468f4021b011ec468fb0210db2b4b0c4e29c462eb4b0c4e29c262e90331099de263a49e49099de263ad9e4b594fcf82627a34b42bcf82627a32b425bf5c0fa2da9204bb180fa2da9202bb10c}
    expiration-seconds: 1209600 # 14 days
email:
  verification:
    token-expiry-minutes: 10
    base-url: ${EMAIL_VERIFICATION_BASE_URL:http://localhost:8080/api/v1/members/verify-email?token=}
frontend:
  oauth2:
    authorized-redirect-uri: ${FRONTEND_OAUTH2_REDIRECT_URI:http://localhost:3000/oauth/callback}