spring:
  datasource-data:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:1521/data_db;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #jdbc-url: ${MYSQL_DATA_URL:jdbc:mysql://localhost:3306/data_db?serverTimezone=Asia/Seoul}
    #username: ${MYSQL_USER:test}
    #password: ${MYSQL_PASSWORD:test}
    hikari:
      pool-name: data-db-hikaricp
      maximum-pool-size: 10
      minimum-idle: 10
  datasource-meta:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:1521/meta_db;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #jdbc-url: ${MYSQL_META_URL:jdbc:mysql://localhost:3306/meta_db?serverTimezone=Asia/Seoul}
    #username: ${MYSQL_USER:test}
    #password: ${MYSQL_PASSWORD:test}
    hikari:
      pool-name: meta-db-hikaricp
      maximum-pool-size: 10
      minimum-idle: 10
  sql:
    init:
      mode: embedded
      continue-on-error: false
      platform: all
      separator: ;
      schema-locations:
        - classpath:/schema-h2-data_db.sql
        #- classpath:/schema-mysql-data_db.sql
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        #show_sql: true
        #format_sql: true
        #highlight_sql: true
        #use_sql_comments: true
    open-in-view: false
  batch:
    jdbc:
      initialize-schema: embedded
      schema: classpath:org/springframework/batch/core/schema-h2.sql
      #schema: classpath:org/springframework/batch/core/schema-mysql.sql
    job:
      enabled: false
  redis:
    client-type: lettuce
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_HOST_PORT:6379}
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  elasticsearch:
    uris:
      - ${ELASTICSEARCH_URI:https://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD}
#logging:
  #level:
    #org.hibernate.sql: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
decorator:
  datasource:
    p6spy:
      logging: slf4j
      enable-logging: true
      multiline: true
    datasource-proxy:
      logging: slf4j
      query:
        enable-logging: false
        log-level: debug
      multiline: true
      json-format: false
      count-query: false
      slow-query:
        enable-logging: false
        log-level: warn
        threshold: 300