spring:
  mail:
    protocol: smtp
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: ${SMTP_FROM}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
          naver:
            client-name: Naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            redirect-uri: ${OAUTH2_NAVER_REDIRECT_URI}
          kakao:
            client-name: Kakao
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email
            redirect-uri: ${OAUTH2_KAKAO_REDIRECT_URI}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  issuer: ${JWT_ISSUER}
  access-token:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    expiration-seconds: 900 # 15 minutes
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_SECRET}
    expiration-seconds: 1209600 # 14 days