name: Notify on Failure

on:
  workflow_run:
    workflows: [ "Build", "Docker" ]
    types:
      - completed

permissions:
  issues: write

jobs:
  notify-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check if Issue Exists
        id: check_issue
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branchName = context.payload.workflow_run.head_branch;
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'all',
              labels: ['build-failure']
            });

            const existingIssue = issues.data.find(issue => issue.title.includes(branchName));
            core.setOutput('issue_exists', existingIssue ? 'true' : 'false');

            if (existingIssue)
              core.setOutput('issue_number', existingIssue.number);

      - name: Create or Update Issue on Failure
        env:
          ISSUE_EXISTS: ${{ steps.check_issue.outputs.issue_exists }}
          ISSUE_NUMBER: ${{ steps.check_issue.outputs.issue_number }}
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          WORKFLOW_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branchName = process.env.BRANCH_NAME;
            const prNumber = process.env.PR_NUMBER ? `#${process.env.PR_NUMBER}` : '';
            const workflowRunUrl = process.env.WORKFLOW_RUN_URL;
            const title = `🚨 Build Failed: ${branchName}${prNumber ? `-${prNumber}` : ''}`;

            const body = `## ❌ Build Failure Detected
            - **Branch:** \`${branchName}\`
            - **PR Number:** ${prNumber ? prNumber : 'N/A'}
            - **Workflow Run:** [🔗 View Logs](${workflowRunUrl})

            Please check the logs and fix the issue.`;

            if (process.env.ISSUE_EXISTS === 'true') {
              const issueNumber = process.env.ISSUE_NUMBER;
              await github.rest.issues.update({
                owner,
                repo,
                issue_number: issueNumber,
                title: title,
                body: body
              });
            } else
              await github.rest.issues.create({
                owner,
                repo,
                title: title,
                body: body,
                labels: ['build-failure']
              });